# Generated by Django 5.2.6 on 2025-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='live',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
